### PR TITLE
Use six module to hande 2vs3 issue of basestring

### PR DESCRIPTION
**Pull request by tp199911**

### CODE REVIEW

**Comment by tp199911** [comment]
As proposed in https://github.com/paulgb/sklearn-pandas/issues/16, this is an implementation that uses the six package to cleanly handle both Py2 and Py3 string types.

**Comment by dukebody** [comment]
I was the one who proposed using six, but perhaps we can replicate the same without pulling the whole package? Since I believe we don't need the rest of six functionality for now.

I.e. write:

	PY2 = sys.version_info[0] == 2
	PY3 = sys.version_info[0] == 3
	if PY3:
	    string_types = str
	else:
	    string_types = basestring

What do you think?

**Comment by tp199911** [comment]
That might indeed be a better idea. This is implemented in PR https://github.com/paulgb/sklearn-pandas/pull/33, I'll leave it up to the maintainers to decide which of the two to merge.

**Comment by dukebody** [comment]
I'm +1 for PR #33. We can always include `six` later if we need more of its functionalities.

@calpaterson ?

**Comment by tp199911** [comment]
I agree, I think PR #338 is the better choice.

**Comment by calpaterson** [comment]
Closing as we merged #33

**Pull request closed without merging**
