### PR TITLE
Remove workaround for sklearn bug #2374

### PR DESCRIPTION
**Pull request by calpaterson**
The bug has since been fixed:

https://github.com/scikit-learn/scikit-learn/issues/2374

### CODE REVIEW

**Comment by dukebody** [comment]
+1 to merging this. It's causing me headaches when working with columns with unicode values (e.g. those returned by django-pandas).

**Comment by calpaterson** [comment]
Hey @paulgb , is it is possible to get some feedback on this pull request?

**Comment by paulgb** [comment]
Merged, thanks Cal!

**Comment by calpaterson** [comment]
Great, thanks!  Not to nag, but do you think you'll get time to release soon?

**Comment by calpaterson** [comment]
Hey Paul, it would really help me if we could get a release with this fix onto pypi.  Do you think you will have time to do that in the near term?  I'm willing to help in any way I can

**Comment by dukebody** [comment]
Hey @calpaterson ! Note that you can directly pull the last version from github in your requirements.txt file as well. It's what I do.

I use this package too and it is core for my company work. Perhaps we could create a fork if @paulgb doesn't have time to work on this?

**Comment by paulgb** [comment]
@calpaterson @dukebody sorry for being a bad maintainer lately; I've changed jobs and no longer use sklearn as frequently. If either of you are interested in maintaining the package, I can add you to the owners on github/pypi. Let me know if it would interest you.

**Comment by dukebody** [comment]
@calpaterson looking at your github profile you might be better suited for the task ;) I have limited knowledge about Python packaging.

**Comment by calpaterson** [comment]
I also use this at work and am happy to maintain this.  My PyPI account is `calpaterson`

**Comment by paulgb** [comment]
That would be great! I've added you to the pypi package as well as the GitHub repo.

**Pull request merged**
